# Generated by Django 2.2.5 on 2019-11-08 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('published', models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 14, 47, 880210))),
                ('genre', models.TextField()),
                ('in_stock', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 14, 47, 881375))),
                ('action', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Book')),
            ],
        ),
    ]
