# Generated by Django 2.2.5 on 2019-11-08 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 25, 8, 278173)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 25, 8, 279580)),
        ),
    ]
