# Generated by Django 2.2.5 on 2019-11-08 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191108_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 27, 14, 496889)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 27, 14, 497681)),
        ),
    ]
